config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :presentations do
    member do
      get :play
    end
    resources :placeholders
  end
  resources :placeholders do
    collection do
      get :news_feed
      get :get_feed_content
      get :get_carousel_photos
    end
  end
end

app/models/feed.rb
include FeedHelper
class Feed < ActiveRecord::Base

  def self.get_wotd #word of the day
    url = 'http://www.thefreedictionary.com/_/WoD/rss.aspx'
    feed_items = self.fetch(url)
    item = feed_items.first
    item_parser(item)
  end

  def self.get_qotd #quote of the day
    url = 'http://www.thefreedictionary.com/_/WoD/rss.aspx?type=quote'
    feed_items = self.fetch(url)
    item = feed_items.first
    item_parser(item)
  end

  def self.get_tdih #this day in history
    url = 'http://www.thefreedictionary.com/_/WoD/rss.aspx?type=history'
    feed_items = self.fetch(url)
    item = feed_items.first
    item_parser(item)
  end

  def self.get_tbday #today's birthday
    url = 'http://www.thefreedictionary.com/_/WoD/rss.aspx?type=birthday'
    feed_items = self.fetch(url)
    item = feed_items.first
    item_parser(item)
  end

  def self.get_news #in the news
    url = 'http://www.thefreedictionary.com/_/WoD/rss.aspx?type=news'
    items = self.fetch(url)
    feed_items = []
    items.each do |item|
      feed_items << item_parser(item)
    end
    feed_items
  end

  def self.get_ndays #greek namedays
    url = 'http://www.greeknamedays.gr/tools/eortologiorssfeed/index.php?langid=gr'
    response = HTTParty.get(url)
    nameday_parser(response.body)
  end

  def self.fetch(url)
    return false unless url.present?
    feed = HTTParty.get(url)
    feed.parsed_response['rss']['channel']['item']
  end

end

app/models/placeholder.rb
class Placeholder < ActiveRecord::Base

  belongs_to :presentation

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base

  has_many :placeholders, :dependent => :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/placeholders_controller.rb
class PlaceholdersController < ApplicationController

  respond_to :html, :xml, :js

  def get_feed_content
    option = params[:option]
    method = "get_#{option}"
    render :json => Feed.send(method.to_sym)
    # case option
    #   when 'wod'
    #   when 'qotd'
    #   when 'tdih'
    #   when 'tbday'
    #   when 'ndays'
    # end
  end

  def news_feed
    render :json => Feed.get_news
  end

  def get_carousel_photos
    client = Dropbox::API::Client.new(:token  => 'hdtci8i08dsyxndt', :secret => 'scfkcdn36wf341j')
    @public_dir = 'https://dl.dropboxusercontent.com/u/195982051/'
    images = client.ls 'public/images'
    @images = images.collect{|x| x.path.sub('public/', '')}
    respond_to do |format|
      format.js{}
    end
  end

end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_filter :find_presentation, :only => [:edit, :update, :destroy]

  layout 'presentation', :only => [:play]

  def index
    @presentations = Presentation.order(:created_at)
  end

  def new
    @presentation = Presentation.new
  end

  def create
    @presentation = Presentation.new(presentation_params)
    if @presentation.save
      flash[:notice] = 'Successfully created presentation.'
      redirect_to presentation_path(@presentation)
    else
      flash[:error] = 'Could not create presentation.'
      render :new
    end
  end

  def edit

  end

  def update
    if @presentation.update_attributes(presentation_params)
      flash[:notice] = 'Successfully updated presentation.'
      redirect_to presentation_path(@presentation)
    else
      flash[:error] = 'Could not update presentation.'
      render :new
    end
  end

  def destroy
    if @presentation.destroy
      flash[:notice] = 'Successfully deleted presentation.'
    else
      flash[:error] = 'Could not delete presentation.'
    end
    redirect_to presentations_path
  end

  def show

  end

  def play

  end

  private
  def presentation_params
    params.require(:presentation).permit(:name)
  end

  def find_presentation
    @presentation = Presentation.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feed_helper.rb
module FeedHelper

  def item_parser(item)
    title = item['title']
    description, url = description_cleaner(item['description'])
    {:title => title, :description => description, :img_url => url}
  end

  def nameday_parser(response)
    parsed = Nokogiri.parse(response)
    description = parsed.xpath('//channel//item//description').text
    {:description => description}
  end

  def description_cleaner(description)
    descr = description.gsub(/Discuss/, '').gsub('\n','').gsub('\t','').gsub('<br clear="all"/>','')
    url = URI.extract(descr, 'http').try(:first)
    descr = descr.gsub(/<img [\w\s\W]+ \/>/, '')
    return descr, url
  end

end

app/helpers/placeholders_helper.rb
module PlaceholdersHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method => 'delete' %></li>
    <li><%= link_to 'Presentations', presentations_path %></li>
<% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <!--<li><%#= link_to 'Sign up', new_user_registration_path %></li>-->
<% end %>
<% if user_signed_in? %>
    <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Britania Signage" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Britania Signage" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/presentation.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Britania Signage" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Britania Signage" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="presentation">
    <main role="main" class="presentation">
      <div class="container-fluid">
       <%= yield %>
          </div>
    </main>
  </body>
</html>

app/views/placeholders/_carousel_photos.html.erb
<% images.each_with_index do |img, i| %>
  <div class="item <%= 'active' if i == 0 %>">
    <%= image_tag (public_dir + img), :class => 'img-responsive', :style => 'max-height: 200px;' %>
  </div>
<% end %>

app/views/placeholders/get_carousel_photos.js.erb
<% if @images.present? %>
  $('.carousel-inner').html('<%= j(render 'placeholders/carousel_photos', :images => @images, :public_dir => @public_dir) %>');
<% end %>

app/views/presentations/_form.html.erb
<%= simple_form_for @presentation, :html => {:class => 'form-horizontal'}, :defaults => {:label_html => {:class => 'col-sm-3'}}, :wrapper => :bootstrap3_horizontal do |f| %>
    <div class="col-md-8 col-md-offset-2">
      <%= f.input :name %>

      <div class="col-md-offset-2">
        <%= f.submit :class => 'btn btn-success' %>
      </div>

    </div>


<% end %>

app/views/presentations/edit.html.erb
<h3>Editing <%= @presentation.name %></h3>

<%= render 'presentations/form' %>

app/views/presentations/index.html.erb
<h3>
  Presentations
  <div class="pull-right">
    <%= link_to 'New', new_presentation_path, :class => 'btn btn-primary' %>
  </div>
</h3>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Created</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @presentations.each do |p| %>
      <tr>
        <td><%= link_to p.name, presentation_path(p) %></td>
        <td><%= p.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_presentation_path(p), :class => 'btn btn-default btn-sm' %>
          <%= link_to 'Delete', presentation_path(p), :method => :delete, :class => 'btn btn-default btn-sm', :data => {:confirm => 'Are you sure?'} %>
          <%= link_to 'Play', play_presentation_path(p), :class => 'btn btn-success btn-sm' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/presentations/new.html.erb
<h3>New Presentation</h3>

<%= render 'presentations/form' %>

app/views/presentations/play.html.erb
<div class="row">
  <div class="col-lg-4">
    <div class="col-lg-4">
      <%= image_tag 'new_logo_britania_2.png' %>
    </div>
    <div class="col-lg-8">
      <div class="date_here text-center">
        <% time_now = DateTime.now %>
        <h3 style="margin-top: 10px;">
          <% day = time_now.day %>
          <%= time_now.strftime("%A") %><br>
          <%= time_now.strftime("#{day.ordinalize} %B %Y") %>
        </h3>
        <h3 style="margin-top: 10px;">
          <span class="text-muted time_here"><%= time_now.strftime('%H:%M:%S') %></span>
        </h3>
      </div>
    </div>

  </div>
  <div class="col-lg-8 text-center">
    <div id="weather">
      <div class="col-lg-5">
        <div id="weather_now">
          <div class="row">
            <div class="col-lg-6"><img class="weather_img" src=""></div>
            <div class="col-lg-6 text-left">
              <h2 style="margin-top: 2px; margin-bottom: 0px;">
                <span class="temp"></span><br>
                <small>
                  <span class="condition"></span><br>
                  <small>
                    Wind <span class="wind"></span>
                  </small>
                </small>

              </h2>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-7">
        <div id="weather_forecast">
          <div class="col-md-3 day1">
            <strong><span class="day_name"></span></strong><br>
            <img class="weather_img" src="">
            <span class="temps small text-muted"></span>
          </div>
          <div class="col-md-3 day2">
            <strong><span class="day_name"></span></strong><br>
            <img class="weather_img" src="">
            <span class="temps small text-muted"></span>
          </div>
          <div class="col-md-3 day3">
            <strong><span class="day_name"></span></strong><br>
            <img class="weather_img" src="">
            <span class="temps small text-muted"></span>
          </div>
          <div class="col-md-3 day4">
            <strong><span class="day_name"></span></strong><br>
            <img class="weather_img" src="">
            <span class="temps small text-muted"></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row" style="max-height: 341px;">
  <div class="col-lg-6">
    <div class="well well-sm">
      <div id="carousel-example-generic" class="carousel slide">
        <!-- Indicators -->
        <div class="carousel-inner">
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="well well-sm">
      <div id="calendar"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <div id="wotd" class="panel panel-small panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <small>Word of the day</small>
          <span class="pull-right title_here"></span>
        </h3>
      </div>
      <div class="panel-body">
        <div class="media">
          <div class="media-body description_here">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div id="qotd" class="panel panel-small panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <small>Quote of the day</small>
          <span class="pull-right title_here"></span>
        </h3>
      </div>
      <div class="panel-body">
        <div class="media">
          <a class="pull-left" href="#">
            <img class="media-object img-thumbnail image_here" src="" >
          </a>
          <div class="media-body">
            <blockquote class="blockquote-reverse blockquote-slim">
              <p class="description_here"></p>
            </blockquote>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div id="ndays" class="panel panel-small panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><small>Today's Namedays</small></h3>
      </div>
      <div class="panel-body">
        <div class="media">
          <div class="media-body description_here"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div id="news_feed_here" class="marquee"></div>
  </div>
</div>

<script type="text/javascript">
  time.auto_update();
  weather_widget.init();
  carousel_imgs.init();
  calendar.init();
  news_feed.init();
  feed_content.init();
</script>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>